#include <iostream>
using namespace std;

int main () {
    // this data type gives the truth value and is only of one byte

    bool isCodingGood = true;
    bool DoYouLikeIt = true;

    cout<<isCodingGood<<endl;
    cout<<DoYouLikeIt<<endl;

    //true value always gives output one and 
    // false value always is zero


    int x = 10,y=10;
    cout<< (x>y)<<endl;
    cout<<x<<y<<endl;

    cout<< (x==y)<<endl;




    return 0;
}